// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace FloorsBySketch
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public  class FloorsBySketchInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public FloorsBySketchInputs(IList<Floors> @floors, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<FloorsBySketchInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @floors});
            }
        
            this.Floors = @floors;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        /// <summary>Draw a list of floor profiles</summary>
        [Newtonsoft.Json.JsonProperty("Floors", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public IList<Floors> Floors { get; set; }
    
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public partial class Floors 
    
    {
        [Newtonsoft.Json.JsonConstructor]
        public Floors(Polygon @boundary, double @elevation, double @thickness)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<Floors>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @boundary, @elevation, @thickness});
            }
        
            this.Boundary = @boundary;
            this.Elevation = @elevation;
            this.Thickness = @thickness;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        [Newtonsoft.Json.JsonProperty("Boundary", Required = Newtonsoft.Json.Required.AllowNull)]
        public Polygon Boundary { get; set; }
    
        /// <summary>The elevation of the floor</summary>
        [Newtonsoft.Json.JsonProperty("Elevation", Required = Newtonsoft.Json.Required.Always)]
        public double Elevation { get; set; } = 0D;
    
        /// <summary>The thickness of the floor</summary>
        [Newtonsoft.Json.JsonProperty("Thickness", Required = Newtonsoft.Json.Required.Always)]
        public double Thickness { get; set; } = 0.3D;
    
        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();
    
        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }
    
    
    }
}